
services:
  database:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"

  backend:
    volumes:
      - ~/.ssh/GIZMO_SSH_KEY_hudson_vu:/app/.ssh/GIZMO_SSH_KEY_hudson_vu:ro
      - ~/.ssh/GIZMO_SSH_KEY_samuel_goodwin:/root/.ssh/GIZMO_SSH_KEY_samuel_goodwin:ro
    build: ./backend
    container_name: backend_service
    restart: always
    environment:
      - DATABASE_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SSH_USERNAME
      - SSH_KEY
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"


  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - SSL_KEY
      - SSL_CRT
      - DEFAULT_USER
      - DEFAULT_PASS
