
services:
  database:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"

  backend:
    volumes:
      - ~/.ssh/GIZMO_SSH_KEY_hudson_vu:/app/.ssh/GIZMO_SSH_KEY_hudson_vu:ro
      - ~/.ssh/GIZMO_SSH_KEY_samuel_goodwin:/root/.ssh/GIZMO_SSH_KEY_samuel_goodwin:ro
    build: ./backend
    container_name: backend_service
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"


  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    env_file:
      - .env
